test_arm:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - arm
  stage: test
  script:
    - cd test
    - make -j2
    - ./test

test_x86_64:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - x86_64
  stage: test
  script:
    - cd test
    - make -j2
    - ./test

