trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - checkout: self
    submodules: true
  - script: |
      cd test
      make -j2
      ./test
    displayName: 'make'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - task: MSBuild@1
    inputs:
      solution: test/test.vcxproj
      configuration: Release

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - checkout: self
    submodules: true
  - script: |
      cd test
      make -j2
      ./test
    displayName: 'make'
